{"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "import React from 'react';\nimport AprilFish from './components/AprilFish';\n\nfunction App(): React.JSX.Element {\n  return (\n    <main className=\"min-h-screen bg-slate-900 flex items-center justify-center overflow-hidden relative font-sans text-slate-200\">\n      <AprilFish />\n      {/* Background Gradient */}\n      <div className=\"absolute inset-0 bg-gradient-to-br from-blue-500/10 via-slate-900 to-purple-500/10\" aria-hidden=\"true\"></div>\n\n      {/* Decorative Orb */}\n      <div\n        className=\"absolute w-96 h-96 bg-blue-500/10 rounded-full blur-3xl animate-pulse motion-reduce:animate-none\"\n        aria-hidden=\"true\"\n      ></div>\n\n      <div className=\"relative z-10 text-center px-4\">\n        <span\n          role=\"img\"\n          aria-label=\"Rocket launching\"\n          className=\"inline-block animate-bounce motion-reduce:animate-none mb-6 text-6xl\"\n        >\n          🚀\n        </span>\n\n        <h1 className=\"text-5xl md:text-7xl font-black mb-4 bg-gradient-to-r from-blue-400 via-purple-500 to-pink-500 bg-clip-text text-transparent forced-colors:text-[CanvasText] break-words text-balance max-w-4xl mx-auto\">\n          "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"projectName") || (depth0 != null ? lookupProperty(depth0,"projectName") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"projectName","hash":{},"data":data,"loc":{"start":{"line":27,"column":10},"end":{"line":27,"column":25}}}) : helper))) != null ? stack1 : "")
    + "\n        </h1>\n\n        <p className=\"text-lg md:text-xl max-w-md mx-auto mb-8 opacity-90 forced-colors:text-[CanvasText]\">\n          React + Tailwind V4 + "
    + ((stack1 = (lookupProperty(helpers,"capitalizeFirst")||(depth0 && lookupProperty(depth0,"capitalizeFirst"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"backend") : depth0),{"name":"capitalizeFirst","hash":{},"data":data,"loc":{"start":{"line":31,"column":32},"end":{"line":31,"column":59}}})) != null ? stack1 : "")
    + " Stack operational.\n        </p>\n\n        <div className=\"px-6 py-3 bg-white/5 backdrop-blur-sm border border-white/10 rounded-full text-white/90 inline-block shadow-xl forced-colors:text-[CanvasText] mb-8\">\n          Feature-Based Architecture ready\n        </div>\n\n        <nav aria-label=\"Documentation links\">\n          <ul className=\"flex flex-wrap gap-4 justify-center items-center\">\n            <li>\n              <a\n                href=\"https://react.dev\"\n                target=\"_blank\"\n                rel=\"noopener noreferrer\"\n                className=\"text-blue-400 hover:text-blue-300 transition-colors font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 rounded px-2 inline-flex items-center gap-1\"\n              >\n                React Docs\n                <span className=\"sr-only\">(opens in a new tab)</span>\n                <svg className=\"w-4 h-4\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" strokeWidth={2} aria-hidden=\"true\">\n                  <path strokeLinecap=\"round\" strokeLinejoin=\"round\" d=\"M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14\" />\n                </svg>\n              </a>\n            </li>\n            <li>\n              <a\n                href=\"https://tailwindcss.com/docs\"\n                target=\"_blank\"\n                rel=\"noopener noreferrer\"\n                className=\"text-blue-400 hover:text-blue-300 transition-colors font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 rounded px-2 inline-flex items-center gap-1\"\n              >\n                Tailwind Docs\n                <span className=\"sr-only\">(opens in a new tab)</span>\n                <svg className=\"w-4 h-4\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" strokeWidth={2} aria-hidden=\"true\">\n                  <path strokeLinecap=\"round\" strokeLinejoin=\"round\" d=\"M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14\" />\n                </svg>\n              </a>\n            </li>\n            <li>\n              <a\n                href=\""
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"backendDocsUrl") || (depth0 != null ? lookupProperty(depth0,"backendDocsUrl") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"backendDocsUrl","hash":{},"data":data,"loc":{"start":{"line":70,"column":22},"end":{"line":70,"column":40}}}) : helper))) != null ? stack1 : "")
    + "\"\n                target=\"_blank\"\n                rel=\"noopener noreferrer\"\n                className=\"text-blue-400 hover:text-blue-300 transition-colors font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 rounded px-2 inline-flex items-center gap-1\"\n              >\n                "
    + ((stack1 = (lookupProperty(helpers,"capitalizeFirst")||(depth0 && lookupProperty(depth0,"capitalizeFirst"))||alias2).call(alias1,(depth0 != null ? lookupProperty(depth0,"backend") : depth0),{"name":"capitalizeFirst","hash":{},"data":data,"loc":{"start":{"line":75,"column":16},"end":{"line":75,"column":43}}})) != null ? stack1 : "")
    + " Docs\n                <span className=\"sr-only\">(opens in a new tab)</span>\n                <svg className=\"w-4 h-4\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" strokeWidth={2} aria-hidden=\"true\">\n                  <path strokeLinecap=\"round\" strokeLinejoin=\"round\" d=\"M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14\" />\n                </svg>\n              </a>\n            </li>\n          </ul>\n        </nav>\n      </div>\n    </main>\n  );\n}\n\nexport default App;\n";
},"useData":true}